---
root: true
parser: '@typescript-eslint/parser'
overrides:
- files:
  - "*.ts"
  parserOptions:
    project:
    - tsconfig.json
    createDefaultProgram: true
  extends:
  - airbnb-base
  - airbnb-typescript/base
  rules:
    import/prefer-default-export: off
    "@typescript-eslint/indent":
    - error
    - 2
    - ignoredNodes:
      - PropertyDefinition[decorators]
      - TSUnionType
      SwitchCase: 1
    class-methods-use-this: off
    "@typescript-eslint/no-explicit-any": error
